version: '3.8'
services:
  server:
    build:
      context: ../Server
    container_name: server-container
    ports:
      - "5000:5000"
    volumes:
      - ../Server:/usr/src/app
    env_file:
      - ../Server/.env # O .env é carregado apenas no serviço "server"
    command: ["npm", "start"]

  project:
    build:
      context: .
    container_name: project-container
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]
