version: '3.9'
services:
  server:
    image: jaderwtb/cd-01_2025-server:1.0
    container_name: server-container
    ports:
      - "4000:4000"
    env_file:
      - ../Server/.env
    command: ["npm", "start"]

  project:
    image: jaderwtb/cd-01_2025-project:1.0
    container_name: project-container
    depends_on:
      - server
    ports:
      - "3000:3000"
    command: sh -c "until nc -z server 4000; do echo 'Waiting for server...'; sleep 2; done && npm start"