# Usar imagem com base em Node -- VERIFICAR SE SERÁ EM NODE
FROM node:18

# Criar diretório de trabalho
WORKDIR /usr/src/app

# Copiando arquivos de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install && npm cache clean --force

# Copiar o restante do código
COPY . .

# Expondo a porta de aplicação (neste caso, a porta 3000)
EXPOSE 3000

# Comando para rodar a aplicação
CMD ["npm", "start"]